namespace ClientBuilder.Common;

/// <summary>
/// Constants used from the Client Builder.
/// </summary>
public static class Constants
{
    /// <summary>
    /// Header text which must be places at the beginning of each locked generated file.
    /// </summary>
    public const string AutoGeneratedHeaderText = @"// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Client Builder.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------";

    /// <summary>
    /// Default Client Builder CORS policy name.
    /// </summary>
    public const string ClientBuilderCorsPolicy = "_CB_CorsPolicy";
}