using System.Collections.Generic;
using ClientBuilder.Common;
using ClientBuilder.Core.Modules;

namespace ClientBuilder.Models;

/// <summary>
/// Response model representing <see cref="ScaffoldModule"/>.
/// </summary>
public class ScaffoldModuleModel
{
    /// <summary>
    /// <inheritdoc cref="ScaffoldModule.Id"/>
    /// </summary>
    public string Id { get; set; }

    /// <summary>
    /// <inheritdoc cref="ScaffoldModule.Order"/>
    /// </summary>
    public int Order { get; set; }

    /// <summary>
    /// <inheritdoc cref="ScaffoldModule.Name"/>
    /// </summary>
    public string Name { get; set; }

    /// <summary>
    /// <inheritdoc cref="ScaffoldModule.ScaffoldTypeName"/>
    /// </summary>
    public string ScaffoldTypeName { get; set; }

    /// <summary>
    /// <inheritdoc cref="ScaffoldModule.Type"/>
    /// </summary>
    public InstanceType Type { get; set; }

    /// <summary>
    /// <inheritdoc cref="ScaffoldModule.ClientId"/>
    /// </summary>
    public string ClientId { get; set; }

    /// <summary>
    /// <inheritdoc cref="ScaffoldModule.Generated"/>
    /// </summary>
    public bool Generated { get; set; }

    /// <summary>
    /// <inheritdoc cref="ScaffoldModule.SourceDirectory"/>
    /// </summary>
    public string SourceDirectory { get; set; }

    /// <summary>
    /// Files that will be generated by the module.
    /// </summary>
    public IEnumerable<ScaffoldModuleFileSystemItemModel> Files { get; set; }

    /// <summary>
    /// Folders that will be generated by the module.
    /// </summary>
    public IEnumerable<ScaffoldModuleFileSystemItemModel> Folders { get; set; }
}